services:
  db:
    image: postgres:15
    container_name: db
    restart: always
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev123
      POSTGRES_DB: nest_dev_db
    env_file:
      - .env
  test-db:
    image: postgres:15
    container_name: db-test
    restart: always
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test123
      POSTGRES_DB: nest_test_db
    env_file:
      - .env.test